version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "node_modules"
          paths: 
            - /src/node_modules
      - run:
          name: "build"
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node_modules"
      - run: npm i
      - run:
          name: "test"
          command: npm run test 
  analyse:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node_modules"
      - run: npm i
      - run:
          name: "analyse"
          command: npm audit
  
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
    
  